id = "adventure-zed"
name = "Adventure Zed"
version = "0.1.0"
schema_version = 1
authors = ["muktadira22"]
description = "Zed Theming for someone who like color palette of 'Adventure Time'"
repository = "https://github.com/muktadira22/adventure-zed"